UPDATE FILMS
SET TITLE = ?,
    DESCRIPTION = ?,
    RELEASE_DATE = ?,
    DURATION = ?,
    RATING_MPA_ID = ?,
    RATE = ?
WHERE FILM_ID = ?;

DELETE FROM FILM_GENRE WHERE FILM_ID = ?;

MERGE INTO FILM_GENRE KEY (FILM_ID, GENRE_ID) VALUES (?, ?);

DELETE FROM FILM_LIKES WHERE FILM_ID = ?;

MERGE INTO FILM_LIKES KEY (FILM_ID, USER_ID) VALUES (?, ?);