INSERT INTO FILMS (TITLE, DESCRIPTION, RELEASE_DATE, DURATION, RATING_MPA_ID, RATE)
VALUES (?, ?, ?, ?, ?, ?);

INSERT INTO FILMS_GENRES (FILM_ID, GENRE_ID)
VALUES (?, ?);

INSERT INTO FILMS_LIKES (FILM_ID, USER_ID)
VALUES (?, ?);