UPDATE FILMS
SET TITLE = ?, DESCRIPTION = ?, RELEASE_DATE = ?, DURATION = ?, RATING_MPA_ID = ?, RATE = ?
WHERE FILM_ID = ?;

SELECT *
FROM FILMS_GENRES_VIEW
WHERE FILM_ID = ?;

DELETE
FROM FILMS_GENRES
WHERE FILM_ID = ?;

MERGE INTO FILMS_GENRES
KEY (FILM_ID, GENRE_ID)
VALUES (?, ?);

SELECT *
FROM FILMS_LIKES
WHERE FILM_ID = ?;

DELETE
FROM FILMS_LIKES
WHERE FILM_ID = ?;

MERGE INTO FILMS_LIKES
KEY (FILM_ID, USER_ID)
VALUES (?, ?);