UPDATE FILMS
SET RATE = RATE - (SELECT COUNT(USER_ID)
                   FROM FILMS_LIKES
                   WHERE FILM_ID = ?)
WHERE FILM_ID = ?;

DELETE
FROM FILMS_LIKES
WHERE FILM_ID = ? AND USER_ID = ?;